custom_components/bms_ble/coordinator.py
custom_components/bms_ble/manifest.json
custom_components/bms_ble/sensor.py

fixed issue that sensors would not update, addresses topic one of https://github.com/patman15/BLE_BMS-HA/issues/2

patch to always update sensors

---

README.md
custom_components/bms_ble/__init__.py
custom_components/bms_ble/binary_sensor.py
custom_components/bms_ble/manifest.json
custom_components/bms_ble/plugins/ogt_bms.py

Implemented the battery charging indicator offered by HA

Charging indicator

---

custom_components/bms_ble/plugins/daly_bms.py
custom_components/bms_ble/plugins/ogt_bms.py

avoid unncessary lambda
stricter typing

optimized register definition

---

custom_components/bms_ble/__init__.py
custom_components/bms_ble/config_flow.py

functionality to upgrade from 1.1.1; note: does not work for 1.2.0-beta

added config entry migration

---

custom_components/bms_ble/binary_sensor.py
custom_components/bms_ble/sensor.py

add ignore type to overwritten classes (unavoidable issue)

added ignore type

---

custom_components/bms_ble/manifest.json
custom_components/bms_ble/plugins/jikong_bms.py

- fixes regular _beeps_ of JK BMS (https://github.com/patman15/BMS_BLE-HA/issues/19)
- should fix rare `unknown` states

make use of continous status updates

---

custom_components/bms_ble/plugins/basebms.py
custom_components/bms_ble/plugins/daly_bms.py
custom_components/bms_ble/plugins/jbd_bms.py
custom_components/bms_ble/plugins/jikong_bms.py
custom_components/bms_ble/plugins/ogt_bms.py
custom_components/bms_ble/plugins/seplos_bms.py
tests/conftest.py
tests/test_config_flow.py
tests/test_daly_bms.py
tests/test_jbd_bms.py
tests/test_jikong_bms.py
tests/test_ogt_bms.py
tests/test_seplos_bms.py

removed BMS device connection status as this is handled by the underlying BleakClient already.

remove connection tracking

---

custom_components/bms_ble/plugins/jbd_bms.py
custom_components/bms_ble/plugins/jikong_bms.py

fixed incorrect bytearray handling, fixes #51

bug: jk/jbd bms sometimes reports 0 values

---

custom_components/bms_ble/coordinator.py

caused issues with JK bms, but could affect also other types

fixed domain identifier to separate devices with same BT name

---

custom_components/bms_ble/coordinator.py
tests/conftest.py

fix unexpecting error fetching BMS data

---

custom_components/bms_ble/plugins/daly_bms.py
tests/test_daly_bms.py

70 daly bms displays wrong temperature since v1.7.0

---

custom_components/bms_ble/__init__.py
custom_components/bms_ble/plugins/daly_bms.py
custom_components/bms_ble/plugins/jbd_bms.py
custom_components/bms_ble/plugins/jikong_bms.py
custom_components/bms_ble/plugins/ogt_bms.py
custom_components/bms_ble/plugins/seplos_bms.py
tests/conftest.py
tests/test_init.py

fixed incorrect BleakClient handling

---

custom_components/bms_ble/plugins/cbtpwr_bms.py
tests/test_cbtpwr_bms.py

recovers more data in case of response misalignment

separate data query from field calculation

---

custom_components/bms_ble/plugins/basebms.py
custom_components/bms_ble/plugins/jbd_bms.py
tests/test_jbd_bms.py

- general timeout
- no None values
- simplified tests

cleanup JBD protocol

---

README.md
custom_components/bms_ble/manifest.json
custom_components/bms_ble/plugins/jbd_bms.py

detailed BT matcher for JBD

---

custom_components/bms_ble/manifest.json
custom_components/bms_ble/plugins/basebms.py
custom_components/bms_ble/plugins/dpwrcore_bms.py
custom_components/bms_ble/plugins/jikong_bms.py
custom_components/bms_ble/plugins/tdt_bms.py
tests/test_tdt_bms.py

- affects JK, TDT, and D-powercore BMS

Fixed reconnect on BMS initialization failure

---

custom_components/bms_ble/plugins/basebms.py

ensure fresh data is fetched even if BMS streams constant messages

Fix protocol sequence bug in JK BMS

---

custom_components/bms_ble/manifest.json
custom_components/bms_ble/plugins/ective_bms.py
tests/advertisement_data.py
tests/test_config_flow.py

Ective has changed their manufacturer ID between 2020 and 2022 from 0xFFFF to 0x0.

adapted Ective identification

---

custom_components/bms_ble/plugins/basebms.py
custom_components/bms_ble/plugins/cbtpwr_bms.py
custom_components/bms_ble/plugins/daly_bms.py
custom_components/bms_ble/plugins/dpwrcore_bms.py
custom_components/bms_ble/plugins/ective_bms.py
custom_components/bms_ble/plugins/ej_bms.py
custom_components/bms_ble/plugins/jbd_bms.py
custom_components/bms_ble/plugins/jikong_bms.py
custom_components/bms_ble/plugins/redodo_bms.py
custom_components/bms_ble/plugins/seplos_bms.py
custom_components/bms_ble/plugins/seplos_v2_bms.py
custom_components/bms_ble/plugins/tdt_bms.py
tests/test_jikong_bms.py

affected (at least) JK, Seplos, Seplos v2, and TDT

Fixed protocol state reset on reconnect

---

README.md
custom_components/bms_ble/manifest.json
custom_components/bms_ble/plugins/jbd_bms.py
tests/advertisement_data.py

add detection for Eleksol

---

custom_components/bms_ble/config_flow.py
custom_components/bms_ble/translations/de.json
custom_components/bms_ble/translations/en.json
custom_components/bms_ble/translations/pt.json
tests/test_config_flow.py

This helps to distinguish devices that have the same name by factory default.

Add MAC identifier to config flow

---

custom_components/bms_ble/manifest.json
custom_components/bms_ble/plugins/redodo_bms.py
tests/advertisement_data.py

Make Redodo pattern more general

---

custom_components/bms_ble/manifest.json
custom_components/bms_ble/plugins/jbd_bms.py
tests/advertisement_data.py
tests/advertisement_ignore.py
tests/test_plugins.py

ECO-WORTHY pattern for classic BT devices

Revert #296 (old ECO-WORTHY detection pattern)

---

tests/advertisement_data.py

Update advertisement typing

---

custom_components/bms_ble/plugins/ecoworthy_bms.py
tests/advertisement_data.py

Correct DCHOUSE/ECO-WORTHY detection pattern
